controller:
  image:
    tag: lts
  serviceType: ClusterIP
  servicePort: 8080

  persistence:
    enabled: true
    size: 8Gi
    storageClass: gp2

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - job-dsl:latest
    - configuration-as-code:latest

  JCasC:
    configScripts:
      pipeline-jobs: |
        jobs:
          - script: >
              pipelineJob('build-images') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/osmarcarmona/eks-test.git')
                        }
                        branches('main')
                      }
                    }
                    scriptPath('Jenkinsfile.build')
                  }
                }
              }
          - script: >
              pipelineJob('deploy-app') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/osmarcarmona/eks-test.git')
                        }
                        branches('main')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }

  sidecars:
    configAutoReload:
      enabled: true

agent:
  enabled: true
  podTemplates:
    helm: |
      - name: helm
        label: helm
        containers:
          - name: helm
            image: alpine/helm:latest
            command: /bin/sh -c
            args: "cat"
            ttyEnabled: true
          - name: kubectl
            image: bitnami/kubectl:latest
            command: /bin/sh -c
            args: "cat"
            ttyEnabled: true
