replicaCount: 1

image:
  repository: 341738837637.dkr.ecr.us-west-2.amazonaws.com/app
  tag: backend-latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  dynamodbTableName: ""
  awsRegion: us-west-2

serviceAccount:
  create: true
  name: backend-sa
  roleArn: ""
