replicaCount: 1

image:
  repository: 341738837637.dkr.ecr.us-west-2.amazonaws.com/app
  tag: frontend-latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  backendServiceName: backend-svc
  backendServicePort: 80
